### ISSUE TITLE
I´m not sure about to start the script

### ISSUE THREAD

**Issue by meins-rbg** [ostrolucky/telegram-stalker#2]
hallo,

know opend the  Win10 Subsystem  and using ubuntu.
I installed telegram-cli and downloaded the code´s that i need.
But how i start the script (tg-stalker.py)?
is it to do in the same line (telegram-cli  ./tg-stalker.py)
becaus if i start telegram-cli i got:
I: config dir=[/home/tele/.telegram-cli] and then a prompt, there i can only use the supported commands.
thanks for helping me.

**Comment by ostrolucky** [comment]
Not `telegram-cli ./tg-stalker.py`, `./tg-stalker.py` like readme mentions

**Comment by meins-rbg** [comment]
Hallo,
thanks fo your very fast answer.
I looked on the redme file.
but if i start first the telegram-cli, i have no prompt for the ./tg-stalker.py.
"
FAIL: 38: can not find command './tg-stalker.py'
"
I´m beginner- sorry.

**Comment by ostrolucky** [comment]
Ok, also try `python tg-stalker.py` or `python3 tg-stalker.py`

**Comment by meins-rbg** [comment]
Hallo,
very kind- thanks really.
i tried and:
> python3 tg-stalker.py
FAIL: 38: can not find command 'python3'
> python tg-stalker.py
FAIL: 38: can not find command 'python'

I have looked for my python Version:

.... tg/telegram-stalker$ python3
Python 3.8.5 (default, Jul 28 2020, 12:59:40)
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>>

Thanks

**Comment by ostrolucky** [comment]
Sorry, but this is too high level support at this point. I cannot provide this level of suport, you are expected to know how to use python scripts when using this project. This issue tracker is meant for bug reports. Please ask your more knowledgable acquintances to help you.

**Comment by meins-rbg** [comment]
Hallo,
thank you, no Problem- i will learn this - without your support it is a little bit a longer way- but for this i´m here.
Thanks
